[tool.bumpversion]
current_version = "0.6.0"
allow_dirty = true

[[tool.bumpversion.files]]
filename = "src/caseutil.py"

[[tool.bumpversion.files]]
filename = "README.md"
search = "/{current_version}/"
replace = "/{new_version}/"
