site_name: caseutil
site_url: https://caseutil.readthedocs.io
repo_url: https://github.com/makukha/caseutil
repo_name: makukha/caseutil
plugins:
  - search
dev_addr: '0.0.0.0:8000'

nav:
  - Get Started: index.md
  - Classification: classification.md
  - Tokenization rules: tokenize.md
  - Alternatives: alternatives.md

exclude_docs: |
  part/*

extra_css:
  - https://use.fontawesome.com/releases/v6.7.0/css/all.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      title: On this page

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    # auto
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
