version: '3'

tasks:

  init:
    desc: Initialize dev environment.
    cmds:
      - brew bundle
      - pyenv install --skip-existing $(pyenv local)
      - task: init:python-versions

  init:python-versions:
    internal: true
    sources:
      - tox.ini
    vars:
      VERSIONS:
        sh: >
          sed -ne '/^env_list/ s/^.*{\(.*\)}.*/\1/; s/,/ /gp' < tox.ini
    cmds:
      - cmd: pyenv install --skip-existing {{.ITEM}}
        for: {var: VERSIONS}

  install:
    desc: Install dev python environment.
    cmds:
      - pdm install --check --dev

  gen:test_readme:
    internal: true
    sources: [README.md]
    generates: [tests/test_readme.txt]
    cmds:
      - pdm run python bin/dev.py get-markdown-code --lang=doctest README.md
          > tests/test_readme.txt

  test:
    desc: Run tests.
    deps: [install]
    vars:
      VERSION: {sh: pdm show --version}
    cmds:
      - pdm build
      - task: gen:test_readme
      - tox run-parallel --installpkg dist/caseutil-{{.VERSION}}-py2.py3-none-any.whl

  version:
    desc: Bump project version. Use task version -- patch|minor|major|...
    cmds:
      - pdm run bump-my-version bump {{.CLI_ARGS}}

  publish:
    desc: Publish package on PyPi.
    cmds:
      - pdm publish
