from typing import IO, List, Optional, Union

def cli(
    argv: Optional[List[str]] = ..., stdin: IO[str] = ..., stdout: IO[str] = ...
) -> None: ...

# helpers
def ioable(value: str, encoding: str = ...) -> str: ...
def stream(item: Union[str, IO[str]]) -> IO[str]: ...
