services:
  dev:
    build:
      context: ..
      dockerfile: .dev/Dockerfile
    hostname: caseutil
    command: bash -c 'task --list; zsh -i'
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - ..:/project
